title: Joonho (Phil) Hwang
url: https://joonho-phil-hwang.github.io
logo: /assets/img/profile2.png
description: ""      # ← 이 줄 추가 (또는 기존 description 교체)
show_downloads: false
theme: jekyll-theme-minimal
google_site_verification: "nJZS8P1pi_xAjH-fMItjcU3Ek_wyatmWAhKJQ20Kj-U"
