title: Joonho Phil Hwang
url: https://joonho-phil-hwang.github.io
logo: /assets/img/profile2.png
description: >
  ğŸ›ï¸ PhD student, Seoul National University<br>
  CV: <a href="https://drive.google.com/file/d/1XJup-ITYEBFdmSa03X9ZxbdulQQxOb-A/view?usp=sharing">Download PDF</a> | Email: <a href="mailto:jhhwang24@snu.ac.kr">jhhwang24@snu.ac.kr</a>
show_downloads: false
theme: jekyll-theme-minimal
google_site_verification: "nJZS8P1pi_xAjH-fMItjcU3Ek_wyatmWAhKJQ20Kj-U"
